# Generated by Django 4.2.16 on 2024-12-18 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_name', models.CharField(max_length=100)),
                ('car_image', models.ImageField(upload_to='car_images/')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('model', models.CharField(max_length=50)),
                ('year', models.PositiveIntegerField()),
                ('color', models.CharField(max_length=50)),
                ('kilometers', models.PositiveIntegerField()),
                ('owner', models.CharField(max_length=20)),
                ('fuel_type', models.CharField(max_length=20)),
                ('transmission', models.CharField(max_length=20)),
                ('engine', models.CharField(max_length=50)),
                ('insurance_validity', models.DateField()),
                ('specifications', models.TextField()),
                ('features', models.TextField()),
            ],
        ),
    ]
