# Generated by Django 4.2.16 on 2024-12-18 11:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='carlisting',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='carlisting',
            name='features',
            field=models.CharField(blank=True, choices=[('air_conditioner', 'Air Conditioner'), ('heater', 'Heater'), ('adjustable_steering', 'Adjustable Steering'), ('digital_clock', 'Digital Clock'), ('navigation_system', 'Navigation System'), ('parking_sensors', 'Parking Sensors')], max_length=200),
        ),
        migrations.AlterField(
            model_name='carlisting',
            name='specifications',
            field=models.CharField(blank=True, choices=[('central_locking', 'Central Locking'), ('driver_airbag', 'Driver Airbag'), ('abs', 'Anti-Lock Braking System'), ('power_door_locks', 'Power Door Locks'), ('adjustable_seats', 'Adjustable Seats'), ('crash_sensor', 'Crash Sensor'), ('rear_camera', 'Rear Camera')], max_length=200),
        ),
    ]
