# Generated by Django 4.2.16 on 2024-12-18 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_carlisting_user_alter_carlisting_features_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Specification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='carlisting',
            name='features',
        ),
        migrations.RemoveField(
            model_name='carlisting',
            name='specifications',
        ),
        migrations.AddField(
            model_name='carlisting',
            name='features',
            field=models.ManyToManyField(blank=True, to='main.feature'),
        ),
        migrations.AddField(
            model_name='carlisting',
            name='specifications',
            field=models.ManyToManyField(blank=True, to='main.specification'),
        ),
    ]
