# Generated by Django 5.1.2 on 2024-12-19 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_wishlist_user'),
    ]

    operations = [
    ]


from django.db import migrations

def create_initial_specs_and_features(apps, schema_editor):
    Specification = apps.get_model('main', 'Specification')
    Feature = apps.get_model('main', 'Feature')
    
    # Create specifications
    specs = [
        'central_locking',
        'driver_airbag',
        'abs',
        'power_door_locks',
        'adjustable_seats',
        'crash_sensor',
        'rear_camera'
    ]
    for spec in specs:
        Specification.objects.get_or_create(name=spec)
    
    # Create features
    features = [
        'air_conditioner',
        'heater',
        'adjustable_steering',
        'digital_clock',
        'navigation_system',
        'parking_sensors'
    ]
    for feature in features:
        Feature.objects.get_or_create(name=feature)

class Migration(migrations.Migration):
    dependencies = [
        ('main', '0006_alter_wishlist_user'), 
    ]
    operations = [
        migrations.RunPython(create_initial_specs_and_features),
    ]
